--REVOKE ALL ON ALL TABLES IN SCHEMA PUBLIC FROM app_role;
--DROP ROLE app_role;

CREATE ROLE app_role;
GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC TO app_role;
--GRANT INSERT ON ALL TABLES IN SCHEMA PUBLIC TO app_role;
--GRANT UPDATE ON ALL TABLES IN SCHEMA PUBLIC TO app_role;
--GRANT DELETE ON ALL TABLES IN SCHEMA PUBLIC TO app_role;

SET ROLE app_role;
--SELECT * FROM motorista;
--INSERT INTO Motorista (CPF, nome, CNH) values (68454977777, 'Ms. Leo Weber', 98769820857);